# Generated by Django 5.1.4 on 2025-01-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(default='test_community', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
