# Generated by Django 5.1.4 on 2025-01-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_community_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
