# Generated by Django 5.1.4 on 2025-01-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_folow',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_follow', to='forum.community'),
        ),
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='forum.community'),
        ),
    ]
