# Generated by Django 5.1.4 on 2025-01-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
