# Generated by Django 5.1.4 on 2025-01-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_rule',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='forum.community'),
            preserve_default=False,
        ),
    ]
