# Generated by Django 5.1.4 on 2025-02-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_communitygroup_communitygroupitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitygroup',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='communitygroup',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='communitygroup',
            name='icon',
            field=models.ImageField(default='images/forum_icons/group_default.png', upload_to='images/forum_icons/'),
        ),
    ]
