# Generated by Django 5.1.4 on 2025-03-06 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_communitygroup_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_word', to='forum.community')),
            ],
            options={
                'unique_together': {('word', 'community')},
            },
        ),
    ]
