# Generated by Django 5.1.4 on 2025-03-06 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_bannedword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_message', to='forum.community')),
            ],
        ),
    ]
