# Generated by Django 5.1.4 on 2025-03-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_automessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/forum_icons/'),
        ),
    ]
