# Generated by Django 5.1.4 on 2025-03-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_community_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
