# Generated by Django 5.1.4 on 2025-03-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_post_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
